/* eslint-disable no-unused-vars */
/* eslint-disable no-var */

var content_head = [
  '# Markdown Editor',
  "",
  "Use built-in Python's `venv`:",
  "",
  "```",
  "py -m venv venv",
  "```",
  "",
  "Activate virtual environment:",
  "",
  "```",
  "venv\\Scripts\\activate",
  "```",
  "",
  "Upgrade `pip` command (optional - recommended):",
  "",
  "```",
  "py -m pip install --upgrade pip",
  "```",
  "",
  "Install required libraries/packages:",
  "",
  "```",
  "pip install -r requirements.txt",
  "```",
].join('\n');

var content = [
  '# Awesome Editor!',
  '',
  '![image](https://uicdn.toast.com/toastui/img/tui-editor-bi.png)',
  '',
  'It has been _released as opensource in 2018_ and has ~~continually~~ evolved to **receive 10k GitHub ⭐️ Stars**.',
  '',
  '## Create Instance',
  '',
  'You can create an instance with the following code and use `getHtml()` and `getMarkdown()` of the [Editor](https://github.com/nhn/tui.editor).',
  '',
  '```js',
  'const editor = new Editor(options);',
  '```',
  '',
  '> See the table below for default options',
  '> > More API information can be found in the document',
  '',
  '| name | type | description |',
  '| --- | --- | --- |',
  '| el | `HTMLElement` | container element |',
  '',
  '## Features',
  '',
  '* CommonMark + GFM Specifications',
  '   * Live Preview',
  '   * Scroll Sync',
  '   * Auto Indent',
  '   * Syntax Highlight',
  '        1. Markdown',
  '        2. Preview',
  '',
  '## Support Wrappers',
  '',
  '> * Wrappers',
  '>    1. [x] React',
  '>    2. [x] Vue',
  '>    3. [ ] Ember',
  '',
].join('\n');

var chartContent = [
  '$$chart',
  ',category1,category2',
  'Jan,21,23',
  'Feb,31,17',
  '',
  'type: column',
  'title: Monthly Revenue',
  'x.title: Amount',
  'y.title: Month',
  'y.min: 1',
  'y.max: 40',
  'y.suffix: $',
  '$$',
  '',
].join('\n');

var codeContent = [
  '```js',
  "console.log('foo')",
  '```', '',
  '```javascript',
  "console.log('bar')",
  '```', '',
  '```html',
  '<div id="editor"><span>baz</span></div>',
  '```', '',
  '```wrong',
  '[1 2 3]',
  '```', '',
  '```clojure',
  '[1 2 3]',
  '```', '',
].join('\n');

var tableContent = ['| @cols=2:merged |', '| --- | --- |', '| table | table2 |', '',].join('\n');

var umlContent = [
  '$$uml',
  'partition Conductor {',
  '  (*) --> "Climbs on Platform"',
  '  --> === S1 ===',
  '  --> Bows',
  '}',
  '',
  'partition Audience #LightSkyBlue {',
  '  === S1 === --> Applauds',
  '}',
  '',
  'partition Conductor {',
  '  Bows --> === S2 ===',
  '  --> WavesArmes',
  '  Applauds --> === S2 ===',
  '}',
  '',
  'partition Orchestra #CCCCEE {',
  '  WavesArmes --> Introduction',
  '  --> "Play music"',
  '}',
  '$$',
].join('\n');

var allPluginsContent = [content_head, content, chartContent, codeContent, tableContent, umlContent].join('\n');
